export const CREATE_GROUP_MODAL = 'CREATE_GROUP_MODAL';
export const USER_PROFILE_MODAL = 'USER_PROFILE_MODAL';
export const CHAT_INFO_MODAL = 'CHAT_INFO_MODAL';
export const EDIT_GROUP_MODAL = 'EDIT_GROUP_MODAL';
export const DELETE_CONF_MODAL = 'DELETE_CONF_MODAL';